#!/usr/bin/python

import sys, re
import requests
import json
from collections import namedtuple

#Get the commit file
commitMessageFile = open(sys.argv[1]) #The first argument is the file
commitMessage = commitMessageFile.read().strip()

#Get Issues from Github
response = requests.get('https://api.github.com/repos/jonathanrocha00/generenciadeconfiguaracaoemudancas2020projeto/issues')
data = json.loads(response.text)
issues = json.loads(response.text, object_hook=lambda d: namedtuple('X', d.keys())(*d.values()))

#Filter open Issues
def filterOpenIssues(issue):
    if issue.state == 'open':
        return True
    else:
        return False
filteredIssues = filter(filterOpenIssues, issues)

#Check if commit message has an Issue number in it
commitMessageHasIssueNumber = False
for issue in filteredIssues:
    if '#'+str(issue.number) in commitMessage:
        commitMessageHasIssueNumber = True
        break

#Prevent commit from being applied if commit message doesn't have Issue number in it
if commitMessageHasIssueNumber:
    sys.exit(0)
else:
    print 'ERROR: Commit message must include Issue number. E.g: Implement button #23'
    sys.exit(1)