#!/usr/bin/python

import sys, re
import requests
import json
from collections import namedtuple
from github import Github
import os


#Get commit files
stream = os.popen('git rev-parse HEAD')
commitHash = stream.read()
stream = os.popen('git diff-tree --no-commit-id --name-only -r ' + commitHash)
commitFiles = stream.read()

#Extract Issue number from Git Log
stream = os.popen('git log -1 HEAD')
gitLog = stream.read()
matchIssueNumber = re.search("(?<=\#)\d+", gitLog)
issueNumber = matchIssueNumber.group(0)

#Get Author name
stream = os.popen('git log -1 --pretty=format:%an')
author = stream.read()

#Get Commit date
stream = os.popen('git log -1 --format=%cd')
commitDate = stream.read()


#Get the commit file
test = open(sys.argv[0])
commitMessage = test.read().strip()
print commitMessage

test2 = open(sys.argv[1])
commitMessage2 = test2.read().strip()
print commitMessage2

test3 = open(sys.argv[2])
commitMessage3 = test3.read().strip()
print commitMessage3




#Create comment on issue
token = '6bf0c4fdc040fa7e2f0833cc18041e652e141981'
g = Github(token);
repo = g.get_repo("jonathanrocha00/generenciadeconfiguaracaoemudancas2020projeto")
issue = repo.get_issue(number=int(issueNumber))

issue.create_comment('<p>Autor: ' + author + '</p><p>Data do commit: ' + commitDate + '<p>Arquivos:</p>' + commitFiles)